# Generated by Django 5.0.1 on 2024-02-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=30)),
                ('eventDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealTime1', models.IntegerField()),
                ('mealTime2', models.IntegerField()),
                ('mealTime3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillName', models.CharField(max_length=30)),
                ('pillStartDate', models.DateField()),
                ('pillEndDate', models.DateField()),
                ('pillDate', models.CharField(max_length=8)),
                ('pillMethod', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepStartTime', models.IntegerField()),
                ('sleepEndTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PillTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillTime', models.IntegerField()),
                ('Pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilltimes', to='parser.pill')),
            ],
        ),
    ]
