# Generated by Django 5.0.1 on 2024-02-06 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pill',
            name='pillEndDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pill',
            name='pillStartDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
