# Generated by Django 5.0.1 on 2024-02-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_event_eventdate_alter_pill_pillenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mealTime1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealTime2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealTime3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleepEndTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleepStartTime',
            field=models.IntegerField(null=True),
        ),
    ]
