# Generated by Django 5.0.1 on 2024-02-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_meal_mealtime1_alter_meal_mealtime2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilltime',
            name='pillTime',
            field=models.IntegerField(null=True),
        ),
    ]
