# Generated by Django 5.0.1 on 2024-02-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_pilltime_pilltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilltime',
            old_name='Pill',
            new_name='pill',
        ),
    ]
