# Generated by Django 5.0.1 on 2024-02-13 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_anyevent_rename_pill_pilltime_pill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anyevent',
            name='eventDateTime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
