# Generated by Django 5.0.1 on 2024-02-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_rename_pill_pilltime_pill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pill',
            name='pillEndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pill',
            name='pillStartDate',
            field=models.DateField(),
        ),
    ]
