# Generated by Django 5.0.1 on 2024-02-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_alter_anyevent_eventdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anyevent',
            name='eventDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
