# Generated by Django 5.0.1 on 2024-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealTime1', models.IntegerField()),
                ('mealTime2', models.IntegerField()),
                ('mealTime3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillName', models.CharField(max_length=50)),
                ('pillStartDate', models.DateField()),
                ('pillEndDate', models.DateField()),
                ('pillDate', models.CharField(max_length=8)),
                ('pillMethod', models.CharField(max_length=20)),
                ('pillTimes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepStartTime', models.IntegerField()),
                ('sleepEndTime', models.IntegerField()),
            ],
        ),
    ]
